name: my-check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"

      - run: make install
      - name: Test ESLint
        run: make lint
      - name: Test Jest
        run: make test
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_ID}}
        with:
          coverageCommand: make test_coverage